### PR TITLE
New response module (#45 implementation)

### PR DESCRIPTION
**Pull request by jomo**
* [x] Complete response module
* [x] Use response module for avatars
* [x] Use response module for index
* [x] Use response module for skins
* [x] Use response module for renders
* [x] Use response module for capes
* [x] Use response module for assets
* Add more test for
  * [x] http headers
  * [x] http body  
  * [x] caching
  * [x] default images
  * [x] redirection
  * [x] error messages

### CODE REVIEW

**Comment by jomo** [comment]
There it is, avatars seem to be working fine with the new module already.
Now our assets and even error messages can have better caching via `Etag`, `Response-Time` is always included and it's overall way nicer.

index, skins, renders, capes, and assets need to be switched to this module yet.

**Comment by jomo** [comment]
So here it is @Jake0oo0, all requests are now using the new `response.js` module.
I found *(and fixed)* a few errors along the way and everything *seems* to be working fine.

Now the last step – all the tests – needs to be worked on :cry:

**Comment by Jake0oo0** [comment]
Have you tested this with iojs 1.8 by chance @jomo? Tried to get it to run on 1.8, but kept receiving an error, so not sure if it's caused by that or not.

**Comment by jomo** [comment]
Hmm, I updated my io.js version recently, not sure if it's 1.8 though.

I will have a look later today

**Comment by jomo** [comment]
That last commit fixes tests, but nothing else was changed. Can you try again and paste the errors?

**Comment by jomo** [comment]
*Note: tests actually passed, but Coveralls failed*
> Coveralls :: Oops, something went wrong (500)

**Comment by Jake0oo0** [comment]
@jomo ``` pathname = path.resolve(pathname);``` broke it again :cry: Like I said in that commit, that method tries to resolve the ```pathname``` to a system path, which on a linux system would resolve to ```/foo/bar``` but on windows it resolves to ```C:/foo/bar```, causing everything to break. I'll try to find an alternative to that method.

**Comment by jomo** [comment]
Hmm, that sucks :disappointed:

**Comment by jomo** [comment]
phew, almost done

**Comment by jomo** [comment]
Tests are failing due to mismatch in crc32 hash for renders. Probably caused by Cairo, I'll check.

**Comment by jomo** [comment]
Great. Spent hours installing a recent version of Cairo, same issue.
The tests are working for me locally. There can be 2 causes for this:

* Server somehow returns different body on travis
* Cairo produces (slightly?) different images on travis

I think the latter is the only one that makes sense, but both my PC and travis are using the latest version now.

Any ideas @Jake0oo0?

**Comment by jomo** [comment]
[crafatar#travis-testing](https://github.com/crafatar/crafatar/tree/travis-testing)

**Comment by jomo** [comment]
Do we still need our own fork of `node-canvas`?

There's only one major difference which removes Pango:
```diff
# binding.gyp
         'with_jpeg%': '<!(./util/has_lib.sh jpeg)',
         'with_gif%': '<!(./util/has_lib.sh gif)',
         # disable pango as it causes issues with freetype.
-        'with_pango%': '<!(./util/has_lib.sh pangocairo)',
+        'with_pango%': 'false',
         'with_freetype%': '<!(./util/has_cairo_freetype.sh)'
       }
     }]
```

Do you remember why we need those changes?
I assume build issues?

There's another change that switches an integer to double, but that has been fixed upstream (using float).

**Comment by jomo** [comment]
* [x] checklist done
* [x] travis builds passing
* [x] coveralls happy
* [x] can be merged
* [x] :shipit:

**Pull request merged**
