### PR TITLE
Rewrite renders

### LINKED ISSUE #32: Fix 3D rendering glitches
For some reason there is a tiny difference to the images, although the helm is empty (at these parts):

```bash
# `compare` comes with ImageMagick
compare \
  "477be35554684c28bdeee4cf11c591d3c88afb77e0b98da893fd7bc318c65184-6-body.png" \
  "477be35554684c28bdeee4cf11c591d3c88afb77e0b98da893fd7bc318c65184-6-bodyhelm.png" \
  "diff.png"
```
The difference is highlighted in red:  
image diff

The two lines on the chin and cheek don't seem to resize on [larger images](https://i.imgur.com/Nfw2Mzu.png) though.

### PR DESCRIPTION
**Pull request by jomo**
This is a WIP pull request that hopefully fixes

* [x] #32  Fix 3D rendering glitches
* [x] #112  Overlay on renders
  * [x] Cut out each part separately
* [x] #117  Don't show opaque helms
  * [x] Detect if each overlay part should be rendered
* [x] #125  Add support for slim models
  * [x] https://github.com/crafatar/crafatar/issues/125#issuecomment-164938928 Workaround for usernames
* [x] #153  Fully transparent pixels need to render black
* [x] make renders isometric
* [x] Fix etags (use crc32 every time)
* [x] Update tests
* [x] Fix travis

**Renders are currently not isometric**
But I think they should be. (?)
isometric

**Each part of the skin will be cut out separately (to a canvas or image)**
This should fix the problem with neighboring pixels leaking colors, as described in https://github.com/crafatar/crafatar/pull/26#issuecomment-67596276 (which *may* be a bug in node-canvas or cairo)

**The single parts will then be placed on the rendering canvas**
We can use `drawImage` and `imageSmoothingEnabled = false` (`patternQuality = "fast"` in node-canvas) to resize the parts at the same time.

**That does't fix the problem with "cracks" in the render**
The issue is that drawing to a [transformed canvas](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform) always uses anti-aliasing and results in (semi-)transparent pixels on edges. This is what all browsers + node-canvas do, so I assume it's correct behavior.
demo screenshot
Click [here for demo](http://jsbin.com/fimavapezi/1/edit?css,js,output) (doesn't work well in Chrome).

**Stitching parts together**
The front side (arms, legs, body) of the render can be stitched together to one image before transforming the canvas, which removes *some* of the "cracks" we're having.
We might have to try merging the anti-aliased edges into each other to avoid the "cracks".

-----

* *The first commit is just me messing around and it will be mostly replaced, but some of the approaches described above are used.*
* *Please ignore the test failures for now*

### CODE REVIEW

**Comment by Jake0oo0** [comment]
Are we sticking with these renders? I thought we wanted to do WebGL at some point?

**Comment by jomo** [comment]
Well, If this works, we can use it. Probably easier than learning how to use it and figuring out how to do this on the server side (OpenGL?).

Perhaps we could also have isometric *and* perspective renders (realistic 3D) using {Web,Open}GL.

By the way, I way playing around with [Isomer](https://github.com/jdan/isomer) (which is really awesome) and noticed it has similar issues as we have if you look closely (so it's definitely not our fault):

isomer glitches

But it's not that bad as the cracks don't seem to be transparent.

**Comment by Jake0oo0** [comment]
I'm still curious as to why it works on Travis...

**Comment by Jake0oo0** [comment]
Was doing a bit of Googling and found some really old [blog post](http://lists.cairographics.org/archives/cairo/2008-March/013394.html)

Looks like it's been an issue for awhile.

>[Hard] Adjacent-polygon fix. Lots of users try to draw a mesh of 
polygons with their edges touching in order to fill the plane with a 
colored image. **Attempting this on Cairo produces artifacts because the 
edges are antialiased and the image has very thin cracks between the 
polygons.** A huge number of graphics produced popular proprietary and 
open-source programs are this way and it is impractical to fix them to 
overlapping shapes. Come up with a solution to this.

Still doesn't explain why it works on Travis.

**Comment by jomo** [comment]
So at least [this is a known problem](https://www.google.com/search?q=%22html5%22+%22canvas%22+%22adjacent%22+%22aliasing%22&gws_rd=cr).

There doesn't seem to be a fix because anti-aliasing is the default for canvas and can't be disabled.
The only solution seems to be trying to merge adjacent edges by moving them "0.5" pixels as I explained in the first post:

>  We might have to try merging the anti-aliased edges into each other to avoid the "cracks".

**Comment by Jake0oo0** [comment]
You say it can't be disabled, but it's just based on a canvas *based* library, so unless it's Cairo doing it, there should be a way to disable it...but according the the link I posted it was Cairo, so probably not possible.

**Comment by jomo** [comment]
I just had this stupid idea that turns out to be working [way better](https://imgur.com/a/gWkpe) than expected.
We can use binary transparency, i.e. pixels are either fully transparent or fully colored.

rainbow gif

**Comment by jomo** [comment]
Added `breaking change` label because image size will change

**Comment by jomo** [comment]
Note to self: consider adding cape to renders

**Comment by jomo** [comment]
(although it would only render the inside of the cape unless we also allow changing the POV)

**Comment by jomo** [comment]
Here's an example of old vs new renders:
example

Each part is cut out separately, the front is rendered onto an extra canvas before being transformed altogether, all cracks seem to be gone (without [binary transparency](https://github.com/crafatar/crafatar/commit/6d12ed685b4bc43b0dac42da6c2dcad1420b3064)) and the renders support slim arms.
However, the arm size is currently hardcoded to 4 pixels because we currently don't store this information.

Also, future changes should be rather simple because we can define position and size with x,y,z coords where 1 unit equals 1 pixel in the skin file.

**Comment by jomo** [comment]
Almost done! Just needs to store slim/classic type in redis and pass it on to the renderer, which might be a bit of a hassle :/

**Comment by jomo** [comment]
And we might want to port some of the stuff over to avatars w/ overlays after we're done here.

**Comment by jomo** [comment]
Here's a comparison of old vs new renders, showcasing various things that have now been fixed:
screenshot

**Comment by jomo** [comment]
Added support for slim models on the caching side. It's **not thoroughly tested** yet and tests will follow.
For some reason travis has some weird errors that I can't reproduce locally. Will need to take a closer look.

**Comment by jomo** [comment]
Hooray, travis is not complaining! :tada:  
_(Apart from the duplicate build that hit the rate limit)_

**Comment by jomo** [comment]
Heh, I was a little scared renders would still have some weird artifacts sometimes, such as user _8_:
8 3d

Fortunately it turns out that's actually the lower edge of the skin's "neckline" showing:
8 bust

phew. :relieved: :sweat_drops:

**Comment by kylerschin** [comment]
epic! we will consider the bug fixes. Thank You!

**Comment by jomo** [comment]
All done! Now for the tests…

**Comment by kylerschin** [comment]
yes! wooo! it works! the api works prefectly!
also, check out my new skin viewer, using craftatar.
kylerschin.github.io/tools/skin

**Comment by jomo** [comment]
Tests are done! :rocket: :+1: :tada: :balloon:  :shipit:

**Pull request merged**
