### PR TITLE
Set 60s cache timeout on errors

### PR DESCRIPTION
**Pull request by jomo**
Fix for #99, not yet ready.

### CODE REVIEW

**Comment by jomo** [comment]
wb @coveralls, you're weird.

**Comment by Jake0oo0** [comment]
Could just put the skin first, it's still called back anyway.

**Comment by jomo** [comment]
What do you mean?

**Comment by Jake0oo0** [comment]
I think currently, we process the skin after the cape. Might make more sense to process the skin first.

**Comment by Jake0oo0** [comment]
Actually, couldn't we make both run completely separate of each other, since we're calling back either way? As long as we have the profile, we can request them at the same time.

**Comment by jomo** [comment]
That's what I'm trying to do, but something is failing

**Comment by Jake0oo0** [comment]
Alright, I'll take a look when I get home. I hated writing that networking sfuff

**Comment by Jake0oo0** [comment]
@jomo don't we have the problem of the cape/skin hash overriding the cached hash, since they're only stored one at a time now?

**Comment by jomo** [comment]
Nope. I [have changed](https://github.com/crafatar/crafatar/blob/0e46019d4084c36985ccd5cd7c37e823a8c5f6d7/modules/cache.js#L124-L131) `cache.save_hash` so that it doesn't set a field in redis to `"."` if it's `undefined`.
So if `skin_hash` is undefined and `cape_hash` is `3f688e...`, it *should* only set the `c` field and ignore the `s` field.

Redis doesn't touch the other fields when setting a new one, as can be seen here:

```py
redis> hmset test foo 1
OK
redis> hmset test bar 2
OK
redis> hgetall test
1) "foo"
2) "1"
3) "bar"
4) "2"
```

**Comment by Jake0oo0** [comment]
Interesting, nice! :D

**Comment by jomo** [comment]
It seems like the tests were already broken in some commit in the master branch and only fail 90% of the time.

It's actually only failing at [this test](https://github.com/crafatar/crafatar/blob/e2d038f78c6d637cf62782af1233f40be6e17a28/test/test.js#L250-L254) which runs 3 times during tests.

I will try to figure out which commit broke it

**Comment by jomo** [comment]
Apparently they are only braking *now* due to @ec0840794baee432ad82afd5f75ba76fd9c4c600. So the issue is still within this PR

**Comment by jomo** [comment]
:shipit:

**Pull request merged**
