### PR TITLE
[WIP] ES6 refactor

### PR DESCRIPTION
**Pull request by RobertHerhold**
I initially started doing this all in one go, but quickly realized that the project was far too large to do one complete refactor. Thus, I have decided to do this with an iterative approach, given that I receive good feedback.

The goal of this PR (and the ones to come) is to refactor the project with ES6 capabilities, namely promises and generators, to result in cleaner code that is easier to read. Although this PR does not deal much with changing the callbacks to promises, it does change the software the server runs on to [koa](https://github.com/koajs/koa), a modern approach to a Node.js server. With koa, there are many improvements that can be made to this project (many of which are not included in this PR):
- [Context](https://github.com/koajs/koa/blob/master/docs/api/context.md) for each request - this makes it so that we can throw an error from anywhere and the logger middleware would be aware of the request (and its ID)
- No callback hell - by replacing callback functions with promise-returning functions, we can avoid messy code such as [here](https://github.com/crafatar/crafatar/blob/6c132f5c51a3b0a05abd3b07dc6776d80c5240a5/lib/helpers.js#L65-L74)
- Less mucking around with request and response objects - by using Koa, we can avoid a lot of the manual labor such as parsing query/path strings, and in general, just shorten the amount of code that needs to be written. One example of this is that in server.js, I have managed to shorten the number of lines by almost 50% while also improving readability

After this PR, the project is a mix of the old and new style, but I hope that by the end of this refactor, it will be almost entirely promisified, and that a lot of unnecessary (in the future) code such as response.js can be eliminated or condensed.

Please, let me know what you think.

### CODE REVIEW

**Comment by Jake0oo0** [comment]
So in #56, we originally removed Express due to the unnecessary overhead, and the fact that we only needed a very simple http server anyway. I haven't been able to properly benchmark your version because I'm getting this error:

```bash
  xxx GET /avatars/Daan_nos?overlay 500 262ms -

  TypeError: Cannot read property 'body' of undefined
      at Object.module.exports.next (/home/jake88/node/crafatar/lib/response.js:31:32)
      at next (native)
      at onFulfilled (/home/jake88/node/crafatar/node_modules/koa/node_modules/co/index.js:65:19)
      at /home/jake88/node/crafatar/node_modules/koa/node_modules/co/index.js:54:5
      at Object.co (/home/jake88/node/crafatar/node_modules/koa/node_modules/co/index.js:50:10)
      at Object.toPromise (/home/jake88/node/crafatar/node_modules/koa/node_modules/co/index.js:118:63)
      at next (/home/jake88/node/crafatar/node_modules/koa/node_modules/co/index.js:99:29)
      at onFulfilled (/home/jake88/node/crafatar/node_modules/koa/node_modules/co/index.js:69:7)
      at tryCallOne (/home/jake88/node/crafatar/node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:37:12)
      at /home/jake88/node/crafatar/node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:103:15
```

for a large portion of the requests. I wouldn't necessarily be against using Koa this time around, but if it does increase memory usage/increases request times, I don't think it's really necessary because of the same reasons that #56 was implemented. Maybe @jomo has a more definitive answer in regards to using Koa.

**Comment by jomo** [comment]
We originally got rid of expressjs because we had a memory leak which we wanted to track down & remove overhead. I don't think it's a problem now to add a lightweight http server if it doesn't add any significant overhead.

Using a single context for both request and response is a great idea. We can somewhat get around passing it to each and every function (as we currently do) by using class instances, so we only have to pass it over when initializing them.

Promises are nice, too. I've wanted to do that for quite a while but never started refactoring :D

----

Using the latest nodejs version with a clean setup, I currently don't get tests to pass:

```js
53 passing (2m)
21 failing

  1) Crafatar Server "before all" hook:
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  2) Crafatar Server "after all" hook:
     TypeError: this.once is not a function
      at Object.Server.close (net.js:1502:12)
      at Context.<anonymous> (test/test.js:856:14)

  3) Crafatar Networking: Cape should not be found:
     Uncaught AssertionError: undefined === null
      at test/test.js:897:16
      at lib/helpers.js:420:7
      at lib/helpers.js:238:9
      at Command.callback (lib/cache.js:150:5)
      at normal_reply (node_modules/redis/index.js:662:21)
      at RedisClient.return_reply (node_modules/redis/index.js:722:9)
      at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnReply (node_modules/redis/index.js:146:18)
      at JavascriptReplyParser.run (node_modules/redis-parser/lib/javascript.js:137:18)
      at JavascriptReplyParser.execute (node_modules/redis-parser/lib/javascript.js:112:10)
      at Socket.<anonymous> (node_modules/redis/index.js:223:27)
      at readableAddChunk (_stream_readable.js:172:18)
      at Socket.Readable.push (_stream_readable.js:130:10)
      at TCP.onread (net.js:542:20)

  4) Crafatar Networking: Avatar should be downloaded:
     Uncaught AssertionError: { status: 2,
  image: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 a0 00 00 00 a0 08 02 00 00 00 04 ad f0 7a === 2
      at test/test.js:937:20
      at lib/helpers.js:290:13
      at lib/skins.js:122:11
      at encoderCb (node_modules/lwip/lib/ImagePrototypeInit.js:594:25)

  5) Crafatar Networking: Avatar should be cached:

      Uncaught AssertionError: false === true
      + expected - actual

      -false
      +true

      at test/test.js:944:20
      at lib/helpers.js:290:13
      at lib/skins.js:122:11
      at encoderCb (node_modules/lwip/lib/ImagePrototypeInit.js:594:25)

  6) Crafatar Networking: Avatar should be downloaded:
     Uncaught AssertionError: { status: 2, image: null, hash: null } === 2
      at test/test.js:937:20
      at lib/helpers.js:300:7
      at Array.<anonymous> (lib/helpers.js:258:13)
      at resume (lib/helpers.js:150:19)
      at lib/helpers.js:196:15
      at Command.callback (lib/cache.js:123:5)
      at normal_reply (node_modules/redis/index.js:662:21)
      at RedisClient.return_reply (node_modules/redis/index.js:722:9)
      at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnReply (node_modules/redis/index.js:146:18)
      at JavascriptReplyParser.run (node_modules/redis-parser/lib/javascript.js:137:18)
      at JavascriptReplyParser.execute (node_modules/redis-parser/lib/javascript.js:112:10)
      at Socket.<anonymous> (node_modules/redis/index.js:223:27)
      at readableAddChunk (_stream_readable.js:172:18)
      at Socket.Readable.push (_stream_readable.js:130:10)
      at TCP.onread (net.js:542:20)

  7) Crafatar Networking: Avatar should be cached:

      Uncaught AssertionError: false === true
      + expected - actual

      -false
      +true

      at test/test.js:944:20
      at lib/helpers.js:300:7
      at lib/helpers.js:238:9
      at Command.callback (lib/cache.js:150:5)
      at normal_reply (node_modules/redis/index.js:662:21)
      at RedisClient.return_reply (node_modules/redis/index.js:722:9)
      at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnReply (node_modules/redis/index.js:146:18)
      at JavascriptReplyParser.run (node_modules/redis-parser/lib/javascript.js:137:18)
      at JavascriptReplyParser.execute (node_modules/redis-parser/lib/javascript.js:112:10)
      at Socket.<anonymous> (node_modules/redis/index.js:223:27)
      at readableAddChunk (_stream_readable.js:172:18)
      at Socket.Readable.push (_stream_readable.js:130:10)
      at TCP.onread (net.js:542:20)

  8) Crafatar Networking: Avatar should be checked:
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  9) Crafatar Networking: Skin should not fail (uuid):
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  10) Crafatar Networking: Render should not fail (full body):
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  11) Crafatar Networking: Render should not fail (only head):
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  12) Crafatar Networking: Cape should not fail (possible cape):
     Uncaught AssertionError: { status: 2, image: null, hash: null } === 2
      at test/test.js:937:20
      at lib/helpers.js:300:7
      at Array.<anonymous> (lib/helpers.js:258:13)
      at resume (lib/helpers.js:150:19)
      at lib/helpers.js:196:15
      at Command.callback (lib/cache.js:123:5)
      at normal_reply (node_modules/redis/index.js:662:21)
      at RedisClient.return_reply (node_modules/redis/index.js:722:9)
      at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnReply (node_modules/redis/index.js:146:18)
      at JavascriptReplyParser.run (node_modules/redis-parser/lib/javascript.js:137:18)
      at JavascriptReplyParser.execute (node_modules/redis-parser/lib/javascript.js:112:10)
      at Socket.<anonymous> (node_modules/redis/index.js:223:27)
      at readableAddChunk (_stream_readable.js:172:18)
      at Socket.Readable.push (_stream_readable.js:130:10)
      at TCP.onread (net.js:542:20)

  13) Crafatar Networking: Avatar should be downloaded:
     Uncaught AssertionError: { status: 2, image: null, hash: null } === 2
      at test/test.js:937:20
      at lib/helpers.js:300:7
      at Array.<anonymous> (lib/helpers.js:258:13)
      at resume (lib/helpers.js:150:19)
      at lib/helpers.js:196:15
      at Command.callback (lib/cache.js:123:5)
      at normal_reply (node_modules/redis/index.js:662:21)
      at RedisClient.return_reply (node_modules/redis/index.js:722:9)
      at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnReply (node_modules/redis/index.js:146:18)
      at JavascriptReplyParser.run (node_modules/redis-parser/lib/javascript.js:137:18)
      at JavascriptReplyParser.execute (node_modules/redis-parser/lib/javascript.js:112:10)
      at Socket.<anonymous> (node_modules/redis/index.js:223:27)
      at readableAddChunk (_stream_readable.js:172:18)
      at Socket.Readable.push (_stream_readable.js:130:10)
      at TCP.onread (net.js:542:20)

  14) Crafatar Networking: Avatar should be cached:
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  15) Crafatar Networking: Avatar should be checked:
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  16) Crafatar Networking: Skin should not fail (uuid):
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  17) Crafatar Networking: Render should not fail (full body):
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  18) Crafatar Networking: Render should not fail (only head):
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  19) Crafatar Errors username should NOT be rate limited (username):
     Error: timeout of 12050ms exceeded. Ensure the done() callback is being called in this test.


  20) Crafatar Networking: Avatar should be downloaded:
     Uncaught AssertionError: { status: 2,
  image: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 a0 00 00 00 a0 08 02 00 00 00 04 ad f0 7a === 2
      at test/test.js:937:20
      at lib/helpers.js:290:13
      at lib/skins.js:122:11
      at encoderCb (node_modules/lwip/lib/ImagePrototypeInit.js:594:25)

  21) Crafatar Networking: Avatar should be cached:
     Uncaught HTTP: 429
      at Request._callback (lib/networking.js:54:13)
      at Request.self.callback (node_modules/request/request.js:199:22)
      at Request.<anonymous> (node_modules/request/request.js:1036:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:963:12)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by RobertHerhold** [comment]
@jomo @Jake0oo0 Thanks for the feedback. I realize that this PR barely works at all, but I wanted to get a reaction from you guys before I proceeded

**Comment by RobertHerhold** [comment]
Is there any particular reason that for redirects, 307 is used instead of 302 [here](https://github.com/crafatar/crafatar/blob/6c132f5c51a3b0a05abd3b07dc6776d80c5240a5/lib/response.js#L80)?

**Comment by jomo** [comment]
It's the correct one. Wikipedia has a good explanation [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection):
> **302 Found**
> This is an example of industry practice contradicting the standard. The HTTP/1.0 specification (RFC 1945) required the client to perform a temporary redirect (the original describing phrase was "Moved Temporarily"), but popular browsers implemented `302` with the functionality of a `303 See Other`. Therefore, HTTP/1.1 added status codes `303` and `307` to distinguish between the two behaviours. However, some Web applications and frameworks use the `302` status code as if it were the `303`.

The description of 307 is "Temporary Redirect", which is exactly what we're intending to do here. See also [RFC 7231 #Redirection](https://tools.ietf.org/html/rfc7231#section-6.4).

**Comment by RobertHerhold** [comment]
Why is [this](https://github.com/crafatar/crafatar/blob/6c132f5c51a3b0a05abd3b07dc6776d80c5240a5/lib/routes/avatars.js#L90-L112) being try caught? Wouldn't the callback take care of any errors?

**Comment by RobertHerhold** [comment]
I've got a bit of an issue trying to use a promisified version of LWIP. I've been trying to figure it out for several hours, so I figured I'd ask you guys. On [these lines](https://github.com/RobertHerhold/crafatar/blob/538e485b9d16edbf144a735624d1dc1b22c0bb90/lib/skins.js#L115-L118), I get this error:

```
Unhandled rejection Error: Unknown arguments configuration,100,100,nearest-neighbor
```

I've double and triple checked the arguments for resize, and yet it's still not right. Do either of you have any idea what the issue might be?

**Comment by jomo** [comment]
Maybe it's because you don't [execute the batch](https://github.com/EyalAr/lwip#executing-a-batch)?

**Comment by RobertHerhold** [comment]
[The `toBuffer` method would also execute the batch first](https://github.com/EyalAr/lwip#execute-batch-and-obtain-a-buffer-object)

**Comment by RobertHerhold** [comment]
I figured it out... Apparently size was a string for some reason, so decree (used by lwip) gave a completely useless error

**Comment by RobertHerhold** [comment]
Why is [this](https://github.com/crafatar/crafatar/blob/6c132f5c51a3b0a05abd3b07dc6776d80c5240a5/lib/routes/avatars.js#L90-L112) being try-caught? Shouldn't the callback take care of any errors?

**Comment by jomo** [comment]
you're right, that one is quite pointless. Can be removed

**Comment by RobertHerhold** [comment]
I'm not sure I understand the point of queuing callbacks to the response from Mojang's API [here](https://github.com/crafatar/crafatar/blob/7570b15320665c768622d654c4bfb648c9547144/lib/helpers.js#L163-L170). In either case of the if statement, `push_request` gets called, and never gets called anywhere else. It would then follow that as soon as `networking.get_profile` returns, there would only ever be one callback queued... Could you help me understand?

**Comment by jomo** [comment]
The reason is pointed out [above](https://github.com/crafatar/crafatar/blob/7570b15320665c768622d654c4bfb648c9547144/lib/helpers.js#L120-L122):
```js
// used by store_images to queue simultaneous requests for identical userId
// the first request has to be completed until all others are continued
// otherwise we risk running into Mojang's rate limit and deleting the cached skin
```

The problem is that Mojang has a very strict rate limit, so we can't issue two requests to them in a short time, which is usually solved by caching. However, when get two simultaneous requests for the same user, we will query Mojang's API for both of these requests as no cached response is available upon receiving the requests. The latter of these queries to Mojang will fail due to the rate limit and result in an error. To fix this problem, we store a list of currently issued outgoing requests and let other requests "subscribe" to its response.

**Comment by jomo** [comment]
@RobertHerhold are you still interested in continuing this PR, do you need help with anything?

**Comment by RobertHerhold** [comment]
@jomo 
Sorry I haven't been active with this PR in quite a while. I am still interested in continuing this PR, but I want to take a different approach from simply "converting" the API to starting off with a more ES6-focused approach. I will definitely be revisiting this sometime in the relatively near future.

**Pull request closed without merging**
